"""
Curriculum definition: topics (roadmap levels 0-10), skills, and the dependency graph.

This is the *structure*, not the content: knowledge comes from the user's library,
questions/explanations/practice are generated at runtime. The graph here is what lets
the Learning Engine decide *what to study next* and *what prerequisite to repair*.
"""

from __future__ import annotations

from typing import Any

LEVELS: list[dict[str, Any]] = [
    {"index": 0, "title": "Programming Foundations", "goal": "Read code, reason about algorithms and complexity"},
    {"index": 1, "title": "Python & Data", "goal": "Manipulate data fluently in Python / NumPy / Pandas / SQL"},
    {"index": 2, "title": "Mathematics for ML", "goal": "Linear algebra, calculus and probability as working tools"},
    {"index": 3, "title": "Classical ML", "goal": "Fit, validate and ship tabular models correctly"},
    {"index": 4, "title": "Advanced ML", "goal": "Ensembles, tuning, causal thinking, robust evaluation"},
    {"index": 5, "title": "Deep Learning", "goal": "Train, debug and optimise neural networks"},
    {"index": 6, "title": "NLP / LLM", "goal": "Tokenisation to transformers to retrieval-augmented systems"},
    {"index": 7, "title": "ML Engineering", "goal": "Serve models: APIs, latency, data contracts, tests"},
    {"index": 8, "title": "MLOps", "goal": "Pipelines, orchestration, registries, observability, CI/CD for ML"},
    {"index": 9, "title": "ML System Design", "goal": "Design end-to-end systems under cost/latency constraints"},
    {"index": 10, "title": "Senior ML Engineer", "goal": "Own the ML platform: scale, reliability, cost, leadership"},
]

# (code, name, level, domain, summary, keywords, est_hours)
TOPICS: list[tuple[str, str, int, str, str, list[str], float]] = [
    ("foundations.code_literacy", "Reading code & trace execution", 0, "programming",
     "How a program actually runs: frames, scope, stack, reading a traceback top-down.",
     ["variable", "scope", "stack", "traceback", "loop", "function", "recursion"], 6),
    ("foundations.algorithms", "Algorithms & data structures", 0, "programming",
     "Arrays, hash maps, stacks/queues, sorting, search, complexity class discipline.",
     ["complexity", "big-o", "hash", "sorting", "binary-search", "tree", "graph", "queue"], 22),
    ("foundations.tools", "Git, shell, environments", 0, "tooling",
     "Version control, virtual environments, package managers, reproducibility basics.",
     ["git", "shell", "venv", "pip", "dependency", "lockfile"], 8),
    ("foundations.testing", "Testing & debugging discipline", 0, "programming",
     "Unit tests, property thinking, reproducible minimal examples, debugger use.",
     ["pytest", "assert", "unit-test", "debugging", "fixture", "regression"], 10),

    ("python.core", "Python language core", 1, "python",
     "Types, comprehensions, dataclasses, exceptions, iterators, context managers, typing.",
     ["python", "comprehension", "dataclass", "iterator", "exception", "typing", "generators"], 18),
    ("python.numpy", "NumPy & vectorisation", 1, "python",
     "Arrays, broadcasting, strides, axis semantics, vectorised thinking vs loops.",
     ["numpy", "ndarray", "broadcasting", "axis", "dtype", "vectorized", "reshape"], 16),
    ("python.pandas", "Pandas & tabular data", 1, "data",
     "DataFrames, joins, groupby, reshaping, time series, categorical handling, memory.",
     ["pandas", "dataframe", "groupby", "merge", "pivot", "dtype", "timeseries"], 18),
    ("python.sql", "SQL for analysts and ML engineers", 1, "data",
     "Joins, window functions, aggregations, query plans, extracting features from warehouses.",
     ["sql", "join", "group-by", "window", "cte", "index", "query-plan"], 14),
    ("python.statistics", "Descriptive & inferential statistics", 1, "math",
     "Distributions, sampling, confidence intervals, hypothesis tests, effect sizes.",
     ["distribution", "variance", "sampling", "confidence-interval", "hypothesis", "p-value", "bootstrap"], 18),
    ("python.software", "Software engineering for ML", 1, "engineering",
     "Modules, packaging, config, logging, CLIs, dependency injection, docstrings.",
     ["module", "package", "logging", "config", "cli", "refactoring"], 12),

    ("math.linear_algebra", "Linear algebra for ML", 2, "math",
     "Vectors, matrices, dot products, norms, eigendecomposition, SVD, matrix calculus basics.",
     ["matrix", "vector", "dot-product", "norm", "eigenvalue", "svd", "rank", "transpose"], 26),
    ("math.calculus", "Derivatives & gradients", 2, "math",
     "Derivatives, partial derivatives, chain rule, Jacobian, directional derivative, convexity.",
     ["derivative", "partial-derivative", "chain-rule", "gradient", "jacobian", "convex", "tangent"], 22),
    ("math.optimization", "Optimization", 2, "math",
     "Objective functions, convexity, Lagrange multipliers, constrained optimisation, convergence.",
     ["optimization", "convexity", "lagrange", "convergence", "local-minimum", "saddle"], 16),
    ("math.probability", "Probability", 2, "math",
     "Conditional probability, Bayes, random variables, expectation, variance, common families.",
     ["probability", "bayes", "conditional", "expectation", "variance", "bernoulli", "gaussian"], 20),
    ("math.info_theory", "Information theory", 2, "math",
     "Entropy, cross-entropy, KL divergence, mutual information, why loss functions look like they do.",
     ["entropy", "cross-entropy", "kl-divergence", "surprise", "mutual-information", "likelihood"], 10),
    ("math.numerical", "Numerical computing", 2, "math",
     "Floating point, stability, conditioning, overflow/underflow, log-sum-exp.",
     ["float", "stability", "overflow", "log-sum-exp", "conditioning", "precision"], 8),

    ("ml.framing", "ML problem framing & data", 3, "ml",
     "Task types, labels, leakage, train/val/test design, offline vs online metrics.",
     ["supervised", "unsupervised", "leakage", "data-split", "label", "baseline", "metric"], 14),
    ("ml.linear_models", "Linear & logistic regression", 3, "ml",
     "Least squares, normal equations, gradient/SGD solvers, regularisation, calibration.",
     ["linear-regression", "logistic-regression", "least-squares", "ridge", "lasso", "softmax", "coefficients"], 22),
    ("ml.gradient_descent", "Gradient descent family", 3, "ml",
     "Batch/mini-batch/SGD, learning rate, momentum, Adam, schedules, diagnostics.",
     ["gradient-descent", "sgd", "learning-rate", "momentum", "adam", "batch-size", "schedule"], 16),
    ("ml.model_evaluation", "Evaluation & metrics", 3, "ml",
     "Confusion matrix, ROC/AUC, PR curves, MAE/RMSE, calibration curves, statistical significance.",
     ["auc", "roc", "precision", "recall", "f1", "rmse", "calibration", "confusion-matrix"], 14),
    ("ml.tree_models", "Trees, forests, boosting", 3, "ml",
     "CART, information gain, bagging, random forests, gradient boosting (XGBoost/LightGBM).",
     ["decision-tree", "random-forest", "boosting", "gini", "information-gain", "xgboost", "lightgbm"], 18),
    ("ml.preparation", "Feature engineering & pipelines", 3, "ml",
     "Encoding, scaling, imputation, datetime features, sklearn Pipeline,ColumnTransformer.",
     ["one-hot", "scaling", "imputation", "pipeline", "column-transformer", "encoding", "feature-selection"], 18),
    ("ml.bias_variance", "Bias-variance & regularisation", 3, "ml",
     "Under/overfitting diagnosis, regularisation paths, learning curves, capacity control.",
     ["bias", "variance", "overfitting", "underfitting", "regularization", "learning-curve", "dropout"], 12),
    ("ml.clustering", "Clustering & dimensionality reduction", 3, "ml",
     "k-means, DBSCAN, PCA, t-SNE/UMAP, representation evaluation.",
     ["kmeans", "clustering", "pca", "dbscan", "umap", "silhouette", "dimensionality-reduction"], 14),
    ("ml.unsupervised", "Anomaly detection & probabilistic ML", 3, "ml",
     "Density estimation, isolation forest, naive Bayes, Bayesian reasoning, priors.",
     ["anomaly", "isolation-forest", "density", "naive-bayes", "prior", "posterior"], 12),

    ("adv.imbalanced", "Imbalanced & costly problems", 4, "ml",
     "Resampling, class weights, threshold tuning, expected cost, ranking metrics.",
     ["imbalance", "smote", "threshold", "class-weight", "cost-matrix", "ranking"], 12),
    ("adv.tuning", "Hyperparameter optimisation", 4, "engineering",
     "Grid/random/Bayesian search, Optuna, early stopping, nested CV, search budgets.",
     ["hyperparameter", "grid-search", "optuna", "bayesian-optimization", "cross-validation", "early-stopping"], 12),
    ("adv.cauchy_features", "Time series & sequence models (classical)", 4, "ml",
     "Seasonality, ARIMA/ETS, backtesting, horizon-aware splits.",
     ["time-series", "seasonality", "arima", "backtest", "lag-features", "horizon"], 14),
    ("adv.causal", "Causal inference & experiments", 4, "data",
     "A/B tests, uplift, confounders, do-intuition, power analysis.",
     ["ab-test", "uplift", "confounder", "power", "treatment-effect", "randomization"], 14),
    ("adv.fairness", "Fairness, robustness, interpretability", 4, "ml",
     "SHAP, permutation importance, group metrics, drift, adversarial sensitivity.",
     ["shap", "interpretability", "fairness", "permutation-importance", "robustness", "drift"], 14),
    ("adv.recommender", "Recommender systems foundations", 4, "ml",
     "Collaborative filtering, matrix factorisation, candidate generation + ranking split.",
     ["collaborative-filtering", "matrix-factorization", "als", "embedding", "recall-ranking", "cold-start"], 16),

    ("dl.foundations", "Neural network foundations", 5, "deep-learning",
     "Neurons, activations, MLPs, forward pass, parameter shapes, initialisation.",
     ["neuron", "activation", "mlp", "init", "forward-pass", "logits", "shapes"], 18),
    ("dl.backprop", "Backpropagation & autograd", 5, "deep-learning",
     "Computational graphs, chain rule implementation, gradients of matrices, vanishing/exploding.",
     ["backpropagation", "autograd", "chain-rule", "computation-graph", "vanishing-gradient", "gradient-check"], 18),
    ("dl.training", "Training dynamics & regularisation", 5, "deep-learning",
     "Loss curves, normalisation layers, dropout, weight decay, mixed precision, checkpointing.",
     ["batchnorm", "layernorm", "dropout", "weight-decay", "amp", "checkpoint", "scheduler"], 16),
    ("dl.pytorch", "PyTorch in practice", 5, "deep-learning",
     "Tensors, autograd, Modules, DataLoader, training loop, device management, DDP intro.",
     ["pytorch", "tensor", "dataloader", "module", "optimizer", "cuda", "autograd"], 20),
    ("dl.cnn", "Convolutional networks", 5, "deep-learning",
     "Convolutions, pooling, receptive fields, ResNet, transfer learning, augmentation.",
     ["convolution", "pooling", "resnet", "augmentation", "transfer-learning", "receptive-field"], 16),
    ("dl.rnn", "Sequence models: RNN/LSTM/GRU", 5, "deep-learning",
     "Recurrence, gating, seq2seq, teacher forcing, why attention replaced them.",
     ["rnn", "lstm", "gru", "seq2seq", "teacher-forcing", "sequence"], 12),
    ("dl.optimization", "Optimisers & scaling laws", 5, "math",
     "Adam/AdamW, second-order intuition, LR finding, gradient clipping, batch scaling.",
     ["adamw", "clipping", "lr-schedule", "batch-size", "scaling-law", "loss-landscape"], 12),
    ("dl.vision_modern", "Modern vision & multimodal", 5, "deep-learning",
     "ViT, detection, segmentation, CLIP-style contrastive learning.",
     ["vit", "detection", "segmentation", "clip", "contrastive", "multimodal"], 14),

    ("nlp.tokenization", "Text preprocessing & tokenisation", 6, "nlp",
     "Unicode, subword BPE/WordPiece/SentencePiece, vocabularies, special tokens.",
     ["tokenizer", "bpe", "sentencepiece", "vocabulary", "unicode", "special-tokens"], 12),
    ("nlp.embeddings", "Word & sentence embeddings", 6, "nlp",
     "word2vec, GloVe, contextual vectors, cosine similarity, semantic search vectors.",
     ["word2vec", "embedding", "cosine-similarity", "sentence-transformers", "vector-search"], 12),
    ("nlp.transformers", "Transformer architecture", 6, "deep-learning",
     "Self-attention, multi-head, positional encoding, encoder/decoder, KV cache.",
     ["attention", "transformer", "multi-head", "positional-encoding", "kv-cache", "encoder", "decoder"], 22),
    ("nlp.pretraining", "Pretraining & fine-tuning", 6, "nlp",
     "LM objectives, masked LM, LoRA/QLoRA, PEFT, data recipes, catastrophic forgetting.",
     ["pretraining", "language-model", "lora", "qlora", "fine-tuning", "peft", "dataset"], 18),
    ("nlp.llm_apps", "LLM application engineering", 6, "engineering",
     "Prompting, structured output, function calling, evals, guardrails, streaming.",
     ["prompt", "json-mode", "function-calling", "guardrails", "evals", "streaming", "few-shot"], 16),
    ("nlp.rag", "Retrieval-augmented generation", 6, "engineering",
     "Chunking, embeddings, hybrid search, reranking, citations, hallucination control, eval of RAG.",
     ["rag", "chunking", "retrieval", "reranking", "citation", "hallucination", "vector-database"], 22),
    ("nlp.inference", "LLM inference optimisation", 6, "engineering",
     "Quantisation, KV cache, batching, speculative decoding, serving throughput/cost.",
     ["quantization", "int8", "kv-cache", "batching", "throughput", "vllm", "latency"], 14),

    ("mle.data_contracts", "Data contracts & feature stores", 7, "engineering",
     "Schema validation, point-in-time correctness, offline/online parity, backfills.",
     ["feature-store", "schema", "pandera", "point-in-time", "backfill", "data-quality"], 14),
    ("mle.serving", "Model serving APIs", 7, "engineering",
     "FastAPI inference service, batching, async, timeouts, model warmup, versioned endpoints.",
     ["fastapi", "inference", "batching", "uvicorn", "openapi", "versioning", "latency"], 18),
    ("mle.package_deploy", "Packaging & deployment", 7, "engineering",
     "Docker images, model artefacts, config/secret hygiene, k8s basics, blue/green.",
     ["docker", "container", "kubernetes", "artifacts", "registry", "deploy", "helm"], 16),
    ("mle.performance", "Latency, throughput & profiling", 7, "engineering",
     "Profilers, CProfile/py-spy, memory, GPU utilisation, cost per request.",
     ["profiling", "py-spy", "benchmark", "memory", "gpu-utilization", "p99"], 12),
    ("mle.testing_ml", "Testing ML systems", 7, "engineering",
     "Golden datasets, invariant tests, property tests, model diff tests, snapshot evals.",
     ["golden-set", "property-testing", "regression", "snapshot", "test-pyramid"], 12),
    ("mle.security", "Privacy & security for ML", 7, "engineering",
     "PII handling, membership inference, prompt injection, sandboxing user code.",
     ["pii", "anonymization", "security", "prompt-injection", "sandbox", "audit-log"], 10),

    ("mlops.pipelines", "Training pipelines & orchestration", 8, "mlops",
     "DAGs, Airflow/Prefect, idempotency, retries, data versioning (DVC).",
     ["airflow", "prefect", "pipeline", "idempotency", "dvc", "retry", "orchestration"], 16),
    ("mlops.registry", "Experiment tracking & model registry", 8, "mlops",
     "MLflow/W&B, run metadata, lineage, promotion gates, approval flows.",
     ["mlflow", "experiment-tracking", "registry", "lineage", "metadata", "promotion"], 12),
    ("mlops.ci", "CI/CD for ML", 8, "mlops",
     "Test-on-PR, model gates, canary release, rollback, reproducible builds.",
     ["cicd", "github-actions", "gate", "canary", "rollback", "reproducibility"], 14),
    ("mlops.monitoring", "Monitoring, drift & alerting", 8, "mlops",
     "Feature drift, prediction distribution, label latency, SLIs/SLOs, incident runbooks.",
     ["drift", "monitoring", "prometheus", "sli", "slo", "alerting", "incident"], 16),
    ("mlops.data_platforms", "Batch & streaming data platforms", 8, "data",
     "Spark, Kafka, warehouses, lakehouse, feature backfills, exactly-once semantics.",
     ["spark", "kafka", "streaming", "warehouse", "lakehouse", "exactly-once"], 16),
    ("mlops.automation", "Retraining & MLOps automation", 8, "mlops",
     "Triggered retraining, champion/challenger, shadow deploy, auto-rollback on degradation.",
     ["retraining", "champion", "shadow", "automation", "feature-drift-trigger"], 12),

    ("design.api_systems", "ML system design fundamentals", 9, "design",
     "Requirements -> architecture -> data flow -> serving -> eval loop, under constraints.",
     ["system-design", "requirements", "trade-off", "bottleneck", "throughput", "availability"], 18),
    ("design.recsearch", "Large-scale ranking & search systems", 9, "design",
     "Candidate generation, coarse/fine ranking, embeddings at scale, freshness vs accuracy.",
     ["retrieval", "ranking", "ann", "faiss", "index", "freshness", "recall"], 18),
    ("design.realtime", "Real-time ML systems", 9, "design",
     "Online features, low-latency joins, streaming inference, fallback policies.",
     ["real-time", "online-features", "latency", "fallback", "streaming-inference"], 14),
    ("design.reliability", "Reliability, capacity & failure design", 9, "design",
     "Backpressure, retries, idempotency, chaos drills, degradation ladder, incident review.",
     ["reliability", "backpressure", "retry", "chaos", "degradation", "postmortem"], 14),
    ("design.cost", "Cost engineering", 9, "design",
     "Cost per prediction, GPU vs CPU, caching, quantisation, autosizing, budget alarms.",
     ["cost", "autoscaling", "cache", "quantization", "spot", "right-sizing"], 12),
    ("design.llm_platform", "Production LLM platforms", 9, "design",
     "Gateway design, eval harness, caching, routing between models, guardrail stack, data flywheel.",
     ["llm-platform", "gateway", "eval-harness", "routing", "cache", "guardrails"], 18),

    ("senior.ownership", "Technical leadership & roadmap", 10, "leadership",
     "Roadmaps, RFCs, evaluation-first culture, mentoring, cross-team trade-offs.",
     ["rfc", "roadmap", "leadership", "mentoring", "stakeholder", "postmortem"], 14),
    ("senior.platform", "ML platform strategy", 10, "engineering",
     "Build vs buy, platform SLAs, multi-tenant training, model governance, audit.",
     ["platform", "governance", "multi-tenant", "buy-vs-build", "policy", "audit"], 14),
    ("senior.research_org", "Reading research & transfer to production", 10, "ml",
     "Paper triage, ablation discipline, reproduction, safe adoption of new methods.",
     ["paper", "ablation", "reproduction", "sota", "benchmark", "transfer"], 12),
    ("senior.incidents", "Senior interview: incident & design depth", 10, "design",
     "Production incidents, ambiguity handling, communicating uncertainty and decisions.",
     ["incident", "ambiguity", "decision-log", "communication", "escalation"], 10),
]

# (code, name, category, difficulty, topic_code, keywords, depends_on)
# category: theory | math | coding | engineering | problem_solving
SKILLS: list[tuple[str, str, str, int, str, list[str], list[str]]] = [
    # ---- level 0
    ("code.trace", "Trace execution and read tracebacks", "coding", 1, "foundations.code_literacy", ["traceback", "stack", "scope", "frame"], []),
    ("code.types_values", "Values, types, mutation vs copy", "coding", 1, "foundations.code_literacy", ["type", "mutable", "copy", "reference"], ["code.trace"]),
    ("code.control_flow", "Branches, loops, functions", "coding", 1, "foundations.code_literacy", ["loop", "if", "function", "return"], ["code.types_values"]),
    ("algo.complexity", "Big-O and complexity reasoning", "theory", 2, "foundations.algorithms", ["big-o", "complexity", "runtime", "asymptotic"], ["code.control_flow"]),
    ("algo.collections", "Arrays, hash maps, sets, stacks", "coding", 2, "foundations.algorithms", ["array", "hashmap", "dict", "stack", "queue", "lookup"], ["code.control_flow"]),
    ("algo.sorting_search", "Sorting and search", "problem_solving", 2, "foundations.algorithms", ["sorting", "binary-search", "merge", "quicksort"], ["algo.complexity", "algo.collections"]),
    ("algo.recursion", "Recursion and divide & conquer", "problem_solving", 3, "foundations.algorithms", ["recursion", "base-case", "divide-conquer"], ["algo.sorting_search"]),
    ("algo.graphs", "Graph traversal basics", "problem_solving", 3, "foundations.algorithms", ["graph", "bfs", "dfs", "topological"], ["algo.recursion"]),
    ("tools.git", "Git workflows", "engineering", 1, "foundations.tools", ["git", "commit", "branch", "merge", "rebase"], []),
    ("tools.env", "Environments and dependencies", "engineering", 1, "foundations.tools", ["venv", "pip", "requirements", "docker"], ["tools.git"]),
    ("test.unit", "Unit tests and fixtures", "engineering", 2, "foundations.testing", ["pytest", "unit-test", "fixture", "mock"], ["code.control_flow"]),
    ("test.debug", "Reproducible minimal example & debugging", "problem_solving", 2, "foundations.testing", ["debugging", "pdb", "minimal-example"], ["test.unit"]),

    # ---- level 1
    ("py.idioms", "Pythonic code: comprehensions, dataclasses, typing", "coding", 2, "python.core", ["comprehension", "dataclass", "typing", "generator", "context-manager"], ["code.types_values"]),
    ("py.oo", "Classes, protocols, dunder methods", "coding", 2, "python.core", ["class", "inheritance", "protocol", "dunder"], ["py.idioms"]),
    ("py.errors", "Exception design and failure paths", "engineering", 2, "python.core", ["exception", "raise", "error-handling"], ["py.idioms"]),
    ("py.async", "Concurrency: threads, asyncio, processes", "engineering", 3, "python.core", ["asyncio", "thread", "multiprocessing", "gil"], ["py.oo"]),
    ("np.arrays", "NumPy array semantics: shape, axis, dtype", "coding", 2, "python.numpy", ["ndarray", "axis", "shape", "dtype"], ["py.idioms"]),
    ("np.broadcast", "Broadcasting and vectorisation", "coding", 3, "python.numpy", ["broadcast", "vectorized", "outer", "einsum"], ["np.arrays"]),
    ("np.linalg_ops", "NumPy linear algebra primitives", "math", 3, "python.numpy", ["matmul", "dot", "norm", "solve", "transpose"], ["np.broadcast"]),
    ("pd.dataframes", "Pandas indexing, joins, groupby", "coding", 2, "python.pandas", ["dataframe", "merge", "groupby", "index"], ["np.arrays"]),
    ("pd.cleaning", "Missing data, dtypes, outliers", "coding", 3, "python.pandas", ["nan", "fillna", "dtype", "outlier", "astype"], ["pd.dataframes"]),
    ("pd.timeseries", "Resampling and windows", "coding", 3, "python.pandas", ["resample", "rolling", "datetime", "freq"], ["pd.cleaning"]),
    ("sql.select", "Relational queries: joins, aggregates", "coding", 2, "python.sql", ["select", "join", "group-by", "having"], ["pd.dataframes"]),
    ("sql.advanced", "Window functions and query planning", "coding", 3, "python.sql", ["window", "rank", "over", "cte", "explain"], ["sql.select"]),
    ("stat.describe", "Summary statistics and distributions", "math", 2, "python.statistics", ["mean", "median", "variance", "quantile", "histogram"], ["np.arrays"]),
    ("stat.inference", "Confidence intervals and tests", "math", 3, "python.statistics", ["confidence-interval", "t-test", "p-value", "bootstrap"], ["stat.describe"]),
    ("se.modularity", "Packaging, config, logging", "engineering", 3, "python.software", ["module", "config", "logging", "packaging"], ["py.errors"]),
    ("se.refactor", "Readability and refactoring", "engineering", 3, "python.software", ["refactor", "naming", "complexity", "solid"], ["se.modularity", "test.unit"]),

    # ---- level 2
    ("linalg.vectors", "Vectors, dot product, norms", "math", 2, "math.linear_algebra", ["vector", "dot-product", "norm", "projection"], ["np.arrays"]),
    ("linalg.matrices", "Matrix multiplication and transforms", "math", 2, "math.linear_algebra", ["matrix", "matmul", "identity", "inverse", "rank"], ["linalg.vectors"]),
    ("linalg.decomposition", "Eigenvalues, SVD, factorisation", "math", 4, "math.linear_algebra", ["eigenvalue", "svd", "decomposition", "spectral"], ["linalg.matrices"]),
    ("linalg.least_squares", "Least squares and normal equations", "math", 3, "math.linear_algebra", ["least-squares", "normal-equations", "pseudo-inverse"], ["linalg.matrices", "stat.describe"]),
    ("calc.functions", "Functions, limits, continuity", "math", 2, "math.calculus", ["function", "limit", "continuity", "domain"], ["linalg.vectors"]),
    ("calc.derivatives", "Derivatives and rates of change", "math", 2, "math.calculus", ["derivative", "slope", "tangent", "rate"], ["calc.functions"]),
    ("calc.partial_gradient", "Partial derivatives and the gradient", "math", 3, "math.calculus", ["partial-derivative", "gradient", "jacobian", "chain-rule"], ["calc.derivatives", "linalg.matrices"]),
    ("calc.optimization_first_order", "First-order optimisation", "math", 3, "math.optimization", ["stationary-point", "convex", "objective", "minimize"], ["calc.partial_gradient"]),
    ("opt.gradient_descent", "Gradient descent as an algorithm", "math", 3, "math.optimization", ["gradient-descent", "step-size", "convergence", "learning-rate"], ["calc.partial_gradient", "opt.optimization_mindset"]),
    ("opt.optimization_mindset", "Loss, constraints and trade-offs", "theory", 3, "math.optimization", ["loss", "constraint", "regularization", "tradeoff"], ["calc.derivatives"]),
    ("opt.convexity", "Convexity, duality, saddle points", "math", 4, "math.optimization", ["convexity", "duality", "lagrange", "saddle"], ["opt.gradient_descent", "linalg.decomposition"]),
    ("prob.basics", "Probability spaces and conditioning", "math", 2, "math.probability", ["probability", "conditional", "independence", "bayes"], ["stat.describe"]),
    ("prob.random_vars", "Random variables, expectation, variance", "math", 3, "math.probability", ["expectation", "variance", "random-variable", "covariance"], ["prob.basics"]),
    ("prob.distributions", "Key distributions and sampling", "math", 3, "math.probability", ["bernoulli", "gaussian", "poisson", "sampling"], ["prob.random_vars"]),
    ("prob.likelihood", "Likelihood, MLE and MAP", "math", 4, "math.probability", ["likelihood", "mle", "map", "estimator"], ["prob.distributions", "calc.derivatives"]),
    ("info.entropy", "Entropy, cross-entropy, KL", "math", 3, "math.info_theory", ["entropy", "cross-entropy", "kl-divergence", "surprise"], ["prob.likelihood"]),
    ("num.stability", "Floating point and numerical stability", "engineering", 3, "math.numerical", ["float", "overflow", "log-sum-exp", "stability"], ["np.broadcast", "prob.distributions"]),

    # ---- level 3
    ("ml.problem_framing", "Framing tasks, labels and baselines", "theory", 2, "ml.framing", ["baseline", "task-type", "label", "objective"], ["stat.inference"]),
    ("ml.data_splits", "Split design and leakage control", "engineering", 3, "ml.framing", ["train-test-split", "leakage", "cross-validation", "stratified"], ["ml.problem_framing", "pd.cleaning"]),
    ("ml.features", "Encoding, scaling, imputation", "coding", 2, "ml.preparation", ["one-hot", "scaling", "imputation", "encoding"], ["pd.cleaning"]),
    ("ml.pipelines", "sklearn Pipeline / ColumnTransformer", "engineering", 3, "ml.preparation", ["pipeline", "column-transformer", "fit-transform"], ["ml.features", "test.unit"]),
    ("ml.linear_regression", "Linear regression theory + implementation", "theory", 2, "ml.linear_models", ["linear-regression", "residual", "coefficients", "r2"], ["linalg.least_squares", "ml.data_splits"]),
    ("ml.linear_regression_impl", "Implement linear regression from scratch", "coding", 3, "ml.linear_models", ["numpy", "closed-form", "gradient"], ["ml.linear_regression", "np.linalg_ops"]),
    ("ml.logistic_regression", "Logistic regression & softmax", "theory", 3, "ml.linear_models", ["logistic", "sigmoid", "softmax", "log-loss", "odds"], ["prob.likelihood", "info.entropy", "ml.linear_regression"]),
    ("ml.gradient_descent_impl", "Implement SGD / mini-batch GD", "coding", 3, "ml.gradient_descent", ["sgd", "minibatch", "vectorized-update"], ["opt.gradient_descent", "np.linalg_ops"]),
    ("ml.optimizers", "Momentum, RMSProp, Adam, schedules", "theory", 3, "ml.gradient_descent", ["momentum", "adam", "rmsprop", "schedule", "warmup"], ["ml.gradient_descent_impl"]),
    ("ml.regularization", "Ridge, lasso, elastic net", "math", 3, "ml.bias_variance", ["ridge", "lasso", "l1", "l2", "penalty"], ["ml.linear_regression", "prob.likelihood"]),
    ("ml.bias_variance", "Bias-variance diagnosis", "theory", 3, "ml.bias_variance", ["bias", "variance", "overfitting", "underfitting", "learning-curve"], ["prob.random_vars", "ml.data_splits"]),
    ("ml.metrics", "Classification and regression metrics", "theory", 2, "ml.model_evaluation", ["auc", "roc", "f1", "rmse", "mae", "precision-recall"], ["ml.problem_framing"]),
    ("ml.calibration", "Probability calibration", "engineering", 3, "ml.model_evaluation", ["calibration", "brier", "reliability-curve", "temperature-scaling"], ["ml.metrics", "prob.likelihood"]),
    ("ml.trees", "Decision trees and splitting criteria", "theory", 2, "ml.tree_models", ["cart", "gini", "information-gain", "pruning"], ["info.entropy", "ml.metrics"]),
    ("ml.ensembles", "Bagging, random forests", "theory", 3, "ml.tree_models", ["bagging", "random-forest", "bootstrap", "feature-importance"], ["ml.trees", "prob.random_vars"]),
    ("ml.boosting", "Gradient boosting (XGBoost/LGBM)", "theory", 3, "ml.tree_models", ["boosting", "xgboost", "lightgbm", "trees", "regularization"], ["ml.ensembles", "opt.gradient_descent"]),
    ("ml.clustering_kmeans", "k-means and variants", "math", 2, "ml.clustering", ["kmeans", "centroids", "inertia", "kmeans++"], ["linalg.vectors", "stat.describe"]),
    ("ml.clustering_density", "Density/DBSCAN + evaluation", "theory", 3, "ml.clustering", ["dbscan", "silhouette", "noise", "distance"], ["ml.clustering_kmeans"]),
    ("ml.dim_reduction", "PCA and manifold methods", "math", 3, "ml.clustering", ["pca", "svd", "variance-explained", "umap"], ["linalg.decomposition"]),
    ("ml.bayesian", "Bayesian reasoning & naive Bayes", "theory", 3, "ml.unsupervised", ["prior", "posterior", "naive-bayes", "conjugate"], ["prob.basics", "ml.trees"]),
    ("ml.anomaly", "Anomaly detection approaches", "problem_solving", 3, "ml.unsupervised", ["isolation-forest", "outlier", "autoencoder", "threshold"], ["ml.clustering_density", "ml.metrics"]),

    # ---- level 4
    ("adv.imbalance", "Imbalanced learning strategies", "problem_solving", 3, "adv.imbalanced", ["class-weight", "smote", "resampling", "threshold"], ["ml.metrics", "ml.calibration"]),
    ("adv.cost_sensitive", "Expected-cost decisioning", "problem_solving", 4, "adv.imbalanced", ["cost-matrix", "utility", "decision-threshold"], ["adv.imbalance"]),
    ("adv.tuning_skills", "Search spaces and tuning loops", "engineering", 3, "adv.tuning", ["hyperparameter", "optuna", "search-space", "early-stopping"], ["ml.data_splits", "ml.regularization"]),
    ("adv.nested_cv", "Nested CV and honest evaluation", "math", 4, "adv.tuning", ["nested-cv", "overfitting-selection", "significance"], ["adv.tuning_skills", "stat.inference"]),
    ("adv.timeseries", "Time series modelling & backtests", "theory", 3, "adv.cauchy_features", ["arima", "seasonality", "backtest", "lag"], ["pd.timeseries", "ml.metrics"]),
    ("adv.causal_inference", "Confounders and treatment effects", "math", 4, "adv.causal", ["confounder", "ate", "uplift", "instrument"], ["stat.inference", "ml.data_splits"]),
    ("adv.experiments", "A/B test design & power", "engineering", 3, "adv.causal", ["ab-test", "power", "mde", "randomization"], ["adv.causal_inference", "stat.inference"]),
    ("adv.interpretability", "SHAP and attribution", "engineering", 3, "adv.fairness", ["shap", "permutation-importance", "attribution"], ["ml.boosting", "adv.nested_cv"]),
    ("adv.fairness_metrics", "Group fairness metrics", "theory", 4, "adv.fairness", ["demographic-parity", "equalized-odds", "bias-audit"], ["adv.interpretability", "ml.calibration"]),
    ("adv.recsys_foundations", "Matrix factorisation & two-tower", "theory", 3, "adv.recommender", ["als", "matrix-factorization", "two-tower", "cold-start"], ["ml.dim_reduction", "ml.calibration"]),
    ("adv.recsys_ranking", "Candidate generation + ranking", "problem_solving", 4, "adv.recommender", ["recall", "ranking", "ltr", "embedding-index"], ["adv.recsys_foundations", "ml.metrics"]),

    # ---- level 5
    ("dl.neuron", "Neurons, activations, MLP forward pass", "theory", 2, "dl.foundations", ["neuron", "relu", "sigmoid", "mlp", "shapes"], ["ml.logistic_regression", "np.linalg_ops"]),
    ("dl.init_norm", "Initialisation and normalisation", "math", 3, "dl.foundations", ["xavier", "he-init", "batchnorm", "layernorm"], ["dl.neuron", "prob.random_vars"]),
    ("dl.backprop", "Backpropagation by hand and in code", "math", 4, "dl.backprop", ["backpropagation", "chain-rule", "gradient", "computation-graph"], ["calc.partial_gradient", "dl.neuron"]),
    ("dl.backprop_impl", "Implement autograd/backprop from scratch", "coding", 4, "dl.backprop", ["autograd", "reverse-mode", "from-scratch"], ["dl.backprop", "np.broadcast"]),
    ("dl.vanishing", "Gradient pathologies & fixes", "problem_solving", 4, "dl.backprop", ["vanishing-gradient", "exploding", "clipping", "residual"], ["dl.backprop", "num.stability"]),
    ("dl.training_loop", "Training loop, checkpointing, reproducibility", "engineering", 3, "dl.training", ["epoch", "checkpoint", "seed", "dataloader"], ["dl.init_norm", "tools.env"]),
    ("dl.regularization", "Dropout, weight decay, augmentation", "theory", 3, "dl.training", ["dropout", "weight-decay", "augmentation", "label-smoothing"], ["ml.regularization", "dl.training_loop"]),
    ("dl.schedules", "LR schedules and optimiser choice", "math", 3, "dl.optimization", ["cosine", "warmup", "adamw", "onecycle"], ["ml.optimizers", "dl.training_loop"]),
    ("dl.pytorch_core", "PyTorch tensors, modules, autograd", "coding", 3, "dl.pytorch", ["pytorch", "tensor", "module", "optimizer", "device"], ["dl.neuron", "np.arrays"]),
    ("dl.pytorch_training", "PyTorch training pipelines at scale", "engineering", 4, "dl.pytorch", ["train-loop", "mixed-precision", "ddp", "cuda"], ["dl.pytorch_core", "dl.schedules"]),
    ("dl.cnn", "Convolutions and vision backbones", "theory", 3, "dl.cnn", ["convolution", "pooling", "resnet", "stride"], ["dl.pytorch_core", "linalg.decomposition"]),
    ("dl.transfer", "Transfer learning & fine-tuning", "engineering", 3, "dl.cnn", ["pretrained", "freeze", "finetune", "head"], ["dl.cnn", "dl.regularization"]),
    ("dl.rnn_seq", "Recurrent models & sequence data", "theory", 3, "dl.rnn", ["lstm", "gru", "hidden-state", "seq"], ["dl.training_loop", "prob.distributions"]),
    ("dl.seq2seq", "Encoder-decoder, beam search", "problem_solving", 4, "dl.rnn", ["seq2seq", "beam-search", "attention"], ["dl.rnn_seq"]),
    ("dl.vit_multimodal", "Vision transformers & contrastive learning", "theory", 4, "dl.vision_modern", ["vit", "clip", "patch", "contrastive"], ["dl.cnn", "dl.seq2seq"]),
    ("dl.scaling", "Batch/LR scaling and optimiser math", "math", 4, "dl.optimization", ["scaling-law", "lr-batch", "second-order", "loss-landscape"], ["dl.schedules", "opt.convexity"]),

    # ---- level 6
    ("nlp.tokenizers", "Tokenisation design and pitfalls", "coding", 3, "nlp.tokenization", ["bpe", "tokenizer", "vocab", "oov", "special-token"], ["py.idioms", "prob.distributions"]),
    ("nlp.embed", "Embedding models and similarity search", "theory", 3, "nlp.embeddings", ["word2vec", "sentence-transformers", "cosine", "ann"], ["linalg.vectors", "dl.transfer"]),
    ("nlp.attention", "Self-attention math", "math", 4, "nlp.transformers", ["attention", "qkv", "softmax", "multi-head", "mask"], ["dl.backprop", "nlp.embed", "info.entropy"]),
    ("nlp.transformer_arch", "Transformer block: residuals, norms, FFN", "theory", 4, "nlp.transformers", ["transformer", "residual", "layernorm", "ffn", "rope"], ["nlp.attention", "dl.init_norm"]),
    ("nlp.kv_cache", "KV cache, decoding strategies", "engineering", 4, "nlp.transformers", ["kv-cache", "greedy", "sampling", "top-p", "beam"], ["nlp.transformer_arch", "dl.pytorch_training"]),
    ("nlp.pretraining", "Language-model objectives & data", "theory", 4, "nlp.pretraining", ["next-token", "masked-lm", "perplexity", "corpus"], ["nlp.transformer_arch", "prob.likelihood"]),
    ("nlp.peft", "LoRA/QLoRA and fine-tuning ops", "engineering", 4, "nlp.pretraining", ["lora", "qlora", "adapter", "sft", "dpo"], ["nlp.pretraining", "dl.transfer", "dl.regularization"]),
    ("llm.prompting", "Prompt design and structured output", "engineering", 2, "nlp.llm_apps", ["prompt", "few-shot", "json-mode", "instructions"], ["nlp.tokenizers", "se.modularity"]),
    ("llm.evals", "LLM evaluation harnesses", "engineering", 4, "nlp.llm_apps", ["eval", "golden-set", "llm-as-judge", "regression-suite"], ["llm.prompting", "adv.nested_cv"]),
    ("llm.tools", "Function calling and agents", "problem_solving", 4, "nlp.llm_apps", ["tool-calling", "agent", "orchestration", "retry"], ["llm.evals", "py.async"]),
    ("rag.chunking", "Chunking strategies and metadata", "engineering", 3, "nlp.rag", ["chunk", "metadata", "overlap", "heading"], ["nlp.tokenizers", "se.modularity"]),
    ("rag.retrieval", "Hybrid retrieval, BM25 + vectors, rerank", "engineering", 4, "nlp.rag", ["bm25", "vector-search", "rerank", "hybrid", "index"], ["nlp.embed", "rag.chunking", "adv.recsys_ranking"]),
    ("rag.grounding", "Citations, groundedness, hallucination control", "engineering", 4, "nlp.rag", ["citation", "groundedness", "refusal", "confidence"], ["rag.retrieval", "llm.evals"]),
    ("rag.pipeline", "RAG system design and cost", "problem_solving", 4, "nlp.rag", ["rag", "latency", "cache", "routing", "index-lifecycle"], ["rag.grounding", "mle.api"]),
    ("llm.quantize", "Quantisation and inference optimisation", "engineering", 4, "nlp.inference", ["int8", "int4", "awq", "gptq", "throughput"], ["nlp.kv_cache", "mle.serving_perf"]),
    ("llm.serving", "LLM serving: batching, streaming, vLLM", "engineering", 4, "nlp.inference", ["continuous-batching", "streaming", "vllm", "queue"], ["llm.quantize", "mle.serving_perf"]),

    # ---- level 7
    ("mle.api", "Inference API design (FastAPI)", "engineering", 3, "mle.serving", ["fastapi", "pydantic", "endpoint", "openapi"], ["py.errors", "se.modularity"]),
    ("mle.serving_perf", "Latency budget, batching, async serving", "engineering", 4, "mle.serving", ["p99", "batching", "timeout", "warmup", "backpressure"], ["mle.api", "py.async"]),
    ("mle.contracts", "Schema validation & data contracts", "engineering", 3, "mle.data_contracts", ["pandera", "pydantic", "schema", "drift"], ["mle.api", "ml.data_splits"]),
    ("mle.feature_store", "Feature stores and online/offline parity", "engineering", 4, "mle.data_contracts", ["feature-store", "point-in-time", "materialization", "freshness"], ["mle.contracts", "sql.advanced"]),
    ("mle.docker", "Containerising ML services", "engineering", 2, "mle.package_deploy", ["docker", "image", "compose", "layers"], ["tools.env"]),
    ("mle.deploy", "Deploy, rollback, config & secrets", "engineering", 3, "mle.package_deploy", ["kubernetes", "helm", "env", "secret", "canary"], ["mle.docker", "tools.git"]),
    ("mle.profiling", "Profilers and optimisation", "engineering", 3, "mle.performance", ["py-spy", "cProfile", "memory", "vectorize"], ["mle.serving_perf", "algo.complexity"]),
    ("mle.ml_testing", "Golden sets and model regression tests", "engineering", 3, "mle.testing_ml", ["golden-set", "snapshot", "property-test", "diff"], ["test.unit", "ml.metrics"]),
    ("mle.security_ml", "ML security: injection, PII, sandboxing", "engineering", 4, "mle.security", ["prompt-injection", "pii", "sandbox", "rate-limit"], ["mle.contracts", "llm.tools"]),

    # ---- level 8
    ("mlops.pipeline_design", "Idempotent DAG design", "engineering", 3, "mlops.pipelines", ["airflow", "prefect", "retry", "idempotency"], ["mle.deploy", "tools.env"]),
    ("mlops.data_versioning", "Data/model lineage & versioning", "engineering", 3, "mlops.pipelines", ["dvc", "lineage", "snapshot", "manifest"], ["mlops.pipeline_design"]),
    ("mlops.tracking", "Experiment tracking & reproducibility", "engineering", 2, "mlops.registry", ["mlflow", "wandb", "run-metadata", "params"], ["dl.training_loop", "mlops.data_versioning"]),
    ("mlops.registry_ops", "Registry, promotion gates, approvals", "engineering", 3, "mlops.registry", ["registry", "alias", "gate", "approval"], ["mlops.tracking", "mle.ml_testing"]),
    ("mlops.cicd", "CI/CD for ML repos", "engineering", 3, "mlops.ci", ["github-actions", "lint", "test", "build"], ["tools.git", "test.unit", "mle.docker"]),
    ("mlops.release", "Canary, shadow, rollback strategies", "engineering", 4, "mlops.ci", ["canary", "shadow", "rollback", "feature-flag"], ["mlops.cicd", "mle.deploy"]),
    ("mlops.monitoring_ops", "Metrics, drift and alert design", "engineering", 3, "mlops.monitoring", ["prometheus", "sli", "alert", "runbook"], ["mle.contracts", "mlops.registry_ops"]),
    ("mlops.label_feedback", "Label latency & feedback loops", "problem_solving", 4, "mlops.monitoring", ["label-delay", "feedback-loop", "ground-truth"], ["mlops.monitoring_ops", "adv.imbalance"]),
    ("mlops.streaming", "Streaming & batch data platforms", "engineering", 4, "mlops.data_platforms", ["kafka", "spark", "windowing", "exactly-once"], ["mle.feature_store", "sql.advanced"]),
    ("mlops.retraining", "Automated retraining policies", "engineering", 4, "mlops.automation", ["retraining-trigger", "champion-challenger", "decay"], ["mlops.monitoring_ops", "adv.tuning_skills", "mlops.release"]),

    # ---- level 9
    ("design.requirements", "Requirements to architecture", "problem_solving", 3, "design.api_systems", ["requirements", "qps", "latency", "constraints"], ["mle.api", "ml.problem_framing"]),
    ("design.data_flow", "End-to-end data flow design", "engineering", 4, "design.api_systems", ["ingestion", "store", "serving", "consistency"], ["design.requirements", "mle.feature_store"]),
    ("design.tradeoffs", "Explicit trade-off analysis", "theory", 4, "design.api_systems", ["tradeoff", "accuracy", "latency", "cost"], ["design.data_flow", "adv.cost_sensitive"]),
    ("design.recall_rank", "Retrieval + ranking at scale", "problem_solving", 4, "design.recsearch", ["ann", "faiss", "index-sharding", "recall"], ["adv.recsys_ranking", "mle.profiling"]),
    ("design.search_freshness", "Index freshness and update strategy", "engineering", 4, "design.recsearch", ["incremental-index", "freshness", "tombstone"], ["design.recall_rank", "mlops.streaming"]),
    ("design.online_ml", "Real-time feature & inference design", "engineering", 4, "design.realtime", ["online-features", "sub-ms", "fallback", "cache"], ["mle.serving_perf", "mlops.streaming"]),
    ("design.failure", "Failure modes and degradation ladder", "problem_solving", 4, "design.reliability", ["timeout", "retry-budget", "degrade", "load-shedding"], ["design.online_ml", "mle.security_ml"]),
    ("design.reliability_ops", "SLOs, capacity, chaos drills", "engineering", 4, "design.reliability", ["slo", "error-budget", "capacity", "chaos"], ["mlops.monitoring_ops", "design.failure"]),
    ("design.cost_model", "Cost modelling per prediction", "math", 4, "design.cost", ["cost-per-request", "utilization", "spot", "cache-hit-rate"], ["mle.profiling", "design.tradeoffs"]),
    ("design.optimization_cost", "Cost/latency optimisation plans", "engineering", 4, "design.cost", ["quantize", "distill", "batch", "right-size"], ["design.cost_model", "llm.quantize"]),
    ("design.llm_gateway", "LLM gateway and routing design", "engineering", 4, "design.llm_platform", ["router", "fallback-model", "cache", "budget"], ["llm.serving", "design.cost_model"]),
    ("design.llm_guardrails", "Guardrail and eval stack for LLM systems", "engineering", 4, "design.llm_platform", ["guardrails", "evals", "red-team", "filters"], ["design.llm_gateway", "llm.evals", "mle.security_ml"]),
    ("design.rag_at_scale", "Production RAG architecture", "problem_solving", 5, "design.llm_platform", ["rag", "index-lifecycle", "citations", "latency-budget"], ["rag.pipeline", "design.llm_guardrails", "design.search_freshness"]),

    # ---- level 10
    ("senior.ownership", "Own outcomes across teams", "engineering", 4, "senior.ownership", ["rfc", "roadmap", "stakeholder", "priority"], ["design.tradeoffs"]),
    ("senior.mentoring", "Mentoring and review culture", "engineering", 3, "senior.ownership", ["code-review", "mentoring", "feedback"], ["senior.ownership"]),
    ("senior.platform_strategy", "Platform build/buy decisions", "theory", 5, "senior.platform", ["platform", "build-vs-buy", "slA", "governance"], ["senior.ownership", "mlops.registry_ops"]),
    ("senior.governance", "Model governance, audit, compliance", "engineering", 4, "senior.platform", ["audit", "policy", "compliance", "risk"], ["senior.platform_strategy", "mle.security_ml"]),
    ("senior.research_reading", "Paper triage and reproduction", "problem_solving", 4, "senior.research_org", ["arxiv", "ablation", "reproduction", "sota"], ["adv.nested_cv", "dl.scaling"]),
    ("senior.evaluation_culture", "Evaluation-first org design", "engineering", 5, "senior.research_org", ["offline-eval", "online-eval", "holdout", "metric-governance"], ["senior.research_reading", "mlops.monitoring_ops"]),
    ("senior.incident_leadership", "Incident command & postmortems", "engineering", 5, "senior.incidents", ["incident", "postmortem", "escalation", "timeline"], ["design.reliability_ops", "senior.ownership"]),
    ("senior.ambiguity", "Design under ambiguity", "problem_solving", 5, "senior.incidents", ["assumptions", "decision-log", "communication"], ["senior.incident_leadership", "design.rag_at_scale"]),
]


def curriculum_rows() -> tuple[list[dict[str, Any]], list[dict[str, Any]], list[tuple[str, str, float]]]:
    """Return (topic dicts, skill dicts, dependency edges by code)."""
    topic_level = {code: level for code, _name, level, *_rest in TOPICS}
    topics = [
        {
            "code": code,
            "name": name,
            "level": level,
            "domain": domain,
            "summary": summary,
            "keywords": keywords,
            "est_hours": hours,
            "order_index": i,
            "prerequisites": [],
        }
        for i, (code, name, level, domain, summary, keywords, hours) in enumerate(TOPICS)
    ]
    skills = []
    for i, (code, name, category, difficulty, topic_code, keywords, deps) in enumerate(SKILLS):
        skills.append(
            {
                "code": code,
                "name": name,
                "category": category,
                "difficulty": difficulty,
                "topic_code": topic_code,
                "level": topic_level.get(topic_code, 0),
                "keywords": keywords,
                "description": f"{name} — assessed by questions, coding tasks and practice at level {topic_level.get(topic_code, 0)}/10.",
            }
        )
    topic_deps: dict[str, set[str]] = {t["code"]: set() for t in topics}
    by_code = {s["code"]: s for s in skills}
    edges: list[tuple[str, str, float]] = []
    for code, _name, _cat, _diff, _topic, _kw, deps in SKILLS:
        for dep in deps:
            if dep in by_code:
                edges.append((code, dep, 1.0))
            else:
                raise ValueError(f"Unknown skill dependency: {dep} (required by {code})")
        # topic-level prerequisites: skills of topic X depend on skills of earlier topics implicitly
    # propagate topic prerequisites from skill deps that cross topics
    for parent, child, _w in edges:
        pt, ct = by_code[parent]["topic_code"], by_code[child]["topic_code"]
        if pt != ct and pt in topic_deps and topic_level.get(ct, 0) < topic_level.get(pt, 0):
            topic_deps[pt].add(ct)
    for topic in topics:
        topic["prerequisites"] = sorted(topic_deps[topic["code"]])
    return topics, skills, edges
